In [22]:
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from numpy import nan
from math import isnan

In [36]:
features = ['GROSS BUILDING FLOOR AREA (ft²)', 'OCCUPANCY', 'PROPERTY TYPE']

In [45]:
data = pd.read_csv('buildings.csv', header='infer')
bad_cols = ['BUILDING ADDRESS', 'BUILDING ID', 'COMPLIANCE STATUS', 'ENERGY STAR SCORE', 
            'ENERGY STAR CERTIFICATION - ELIGIBILITY',
            'ENERGY STAR CERTIFICATION - LAST APPROVAL DATE',
            'ENERGY STAR CERTIFICATION - YEAR(S) CERTIFIED', 'ENTITY RESPONSIBLE FOR BENCHMARK', 
            'INDOOR WATER USE (kgal)', 'INDOOR WATER USE INTENSITY (gal/ft²)', 'OUTDOOR WATER USE (kgal)',
            'PROGRAM YEAR', 'WEATHER NORMALIZED SITE ENERGY USE INTENSITY (EUI) (kBtu/ft²)',
            'WEATHER NORMALIZED SOURCE ENERGY USE INTENSITY (EUI) (kBtu/ft²)', 'AIN',
            'LADBS Building Category']
data = data.drop(bad_cols, axis=1)
data = data.dropna()
a = newdata.columns.tolist()
for col in a:
    try:
        data = data[data[col] != 'Not Available']
    except:
        pass

X = data[features]
y = data['CARBON DIOXIDE EMISSIONS (Metric Ton CO2e)']

if 'PROPERTY TYPE' in features:
    property_types = X['PROPERTY TYPE'].unique().tolist()
    # residential = 0, commercial = 1, office/industrial = 2, public = 3, mixed = 4 miscellaneous = 5
    property_map = {'Multifamily Housing': 0,
             'Library': 3,
             'Hotel': 1,
             'Manufacturing/Industrial Plant': 2,
             'Other': 5,
             'Mixed Use Property': 4,
             'Office': 2,
             'Hospital (General Medical & Surgical)': 3,
             'Medical Office': 3,
             'Distribution Center': 2,
             'Self-Storage Facility': 1,
             'Strip Mall': 1,
             'K-12 School': 3,
             'Other - Recreation': 3,
             'Non-Refrigerated Warehouse': 2,
             'Residential Care Facility': 0,
             'Other - Utility': 3,
             'Parking': 5,
             'Refrigerated Warehouse': 2,
             'Lifestyle Center': 1,
             'Food Service': 1,
             'Fire Station': 3,
             'Other - Lodging/Residential': 0,
             'Retail Store': 1,
             'Senior Care Community': 0,
             'Supermarket/Grocery Store': 1,
             'Enclosed Mall': 1,
             'College/University': 3,
             'Other - Public Services': 3,
             'Museum': 1,
             'Laboratory': 2,
             'Worship Facility': 3,
             'Other - Entertainment/Public Assembly': 3,
             'Performing Arts': 3,
             'Bank Branch': 2,
             'Mailing Center/Post Office': 3,
             'Vocational School': 3,
             'Data Center': 2,
             'Other - Mall': 1,
             'Other - Services': 1,
             'Energy/Power Station': 2,
             'Automobile Dealership': 1,
             'Police Station': 3,
             'Financial Office': 2,
             'Indoor Arena': 3,
             'Repair Services (Vehicle, Shoe, Locksmith, etc.)': 1,
             'Social/Meeting Hall': 3,
             'Movie Theater': 1,
             'Food Sales': 1,
             'Restaurant': 1,
             'Immeuble � logements multiples': 5,
             'Transportation Terminal/Station': 3,
             'Residence Hall/Dormitory': 0,
             'Wholesale Club/Supercenter': 1,
             'Pre-school/Daycare': 1,
             'Fitness Center/Health Club/Gym': 1,
             'Other - Specialty Hospital': 3,
             'Ice/Curling Rink': 1,
             'Ambulatory Surgical Center': 3,
             'Other - Restaurant/Bar': 1,
             'Bureau': 3,
             'Outpatient Rehabilitation/Physical Therapy': 1,
             'Bowling Alley': 1,
             'Convention Center': 3,
             'Other - Technology/Science': 3,
             'Other - Education': 3,
             'Urgent Care/Clinic/Other Outpatient': 3,
             'Stationnement': 5,
             'Personal Services (Health/Beauty, Dry Cleaning, etc.)': 1,
             'Stadium (Open)': 3,
             'Courthouse': 3,
             'Roller Rink': 1,
             'Adult Education': 3,
             'Convenience Store without Gas Station': 1,
             'Convenience Store with Gas Station': 1,
             'Veterinary Office': 2}
    property_map2 = {pType : index for index, pType in enumerate(property_types)}
    X['PROPERTY TYPE'] = X.apply(lambda row: property_map[row['PROPERTY TYPE']], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y)
model = LinearRegression()
model.fit(X_train, y_train)
predicted_results = model.predict(X_test)
print("R2 score: " + str(metrics.r2_score(y_test, predicted_results)))
print("Explained variance score: " + str(metrics.explained_variance_score(y_test, predicted_results)))

R2 score: -0.007268559340572356
Explained variance score: -0.006913996215712537

/anaconda3/lib/python3.6/site-packages/pandas/core/ops.py:1164: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [46]:
X

       GROSS BUILDING FLOOR AREA (ft²)  OCCUPANCY  PROPERTY TYPE
0                              97547.0       95.0              0
1                              63821.0       95.0              0
2                              10500.0      100.0              3
4                              68230.0      100.0              0
5                              48388.0       95.0              0
6                             150962.0       60.0              1
9                             201000.0       95.0              0
11                             12400.0      100.0              5
12                            423801.0      100.0              0
14                             34112.0      100.0              4
16                             98324.0       95.0              0
17                             30632.0       95.0              0
18                             80000.0      100.0              0
19                            115419.0      100.0              2
23                            148782.0       95.0              0
25                             27750.0      100.0              0
28                            756397.0      100.0              3
31                             29580.0       95.0              0
32                            120000.0      100.0              2
34                            116961.0      100.0              3
35                            232500.0      100.0              2
36                             55564.0      100.0              1
38                             26692.0       85.0              4
40                             82491.0      100.0              0
43                             60930.0      100.0              1
45                             60000.0      100.0              3
48                            110745.0       90.0              0
53                             58380.0       90.0              1
54                             21420.0      100.0              2
55                            202905.0      100.0              2
...                                ...        ...            ...
29198                           9040.0      100.0              3
29200                          20393.0      100.0              1
29201                          17619.0      100.0              3
29203                          23400.0      100.0              2
29204                          27945.0       90.0              0
29208                          36500.0      100.0              3
29209                          61569.0      100.0              3
29211                         259330.0       50.0              5
29213                         110833.0      100.0              3
29217                         170562.0       80.0              3
29219                          51859.0       50.0              1
29220                         624222.0      100.0              3
29221                          17619.0      100.0              3
29222                          46677.0      100.0              3
29223                          47676.0       95.0              2
29224                          27734.0       95.0              2
29225                          47319.0       95.0              5
29227                          32090.0       95.0              2
29228                         298000.0       80.0              3
29229                          90900.0       95.0              2
29230                         105000.0      100.0              0
29234                          17000.0       80.0              3
29235                          15040.0      100.0              3
29237                          92920.0      100.0              2
29240                          20712.0      100.0              5
29242                          45000.0      100.0              3
29245                          92090.0       50.0              2
29248                          38788.0      100.0              2
29249                          53800.0      100.0              3
29251                         491023.0      100.0              3

[11017 rows x 3 columns]